source "https://rubygems.org"

gem "json", "~> 2.13"
gem "csv"
gem "base64"
gem "bigdecimal"
gem "mutex_m"
gem "net-pop"
gem "net-smtp"
gem "observer"
gem "pstore"
gem "resolv-replace"
gem "rinda"
gem "syslog"
# Only load the source gemspec, never a copy from a previous site build.
gemspec glob: "minimal-mistakes-jekyll.gemspec"
